### ISSUE TITLE
yt Transformer

### ISSUE THREAD

**Issue by BenGalewsky** [pondd-project/pondd#14]
_As an astrophysicist I want to specify a query on yt data using raw python so I can obtain a slice of data for my analysis._

The standard way of specifying volumetric queries for this data is yt. The analyzer will provide in the `selection` property of the transform a string representation of a python function. This function will accept an open [yt dataset](https://yt-project.org/docs/dev/reference/api/yt.data_objects.static_output.html#yt.data_objects.static_output.Dataset) as an argument and return a numpy array,

# Assumptions
1. There will be a new raw-python codgen service that accepts a string containing a python function and will simply write it out to the code ConfigMap.
2. The yt transformer will download the file indicated in the file path and unzip if necessary
3. The yt transformer will import that generated function and wrap the call with 

```
import yt
ds = yt.load("Enzo_64/DD0043/data0043")
```

# Acceptance Criteria
Given I have a ServiceX Transform with a selection string of:
```python
def transform_yt(ds):
    slc = ds.r[ds.domain_center[0], :, :].plot(("gas", "density"))
    slc.frb[("gas", "density")].d  # this is numpy array, even more basic than Awkward Array
    return sac
```
and a valid yt dataset When the transform completes Then I should have a set of parquet files containing gas density data

**Comment by Michael-D-Johnson** [comment]
Initial version here: https://github.com/pondd-project/ServiceX_yt_Transformer. Can iterate as we get feedback from yt users.
