### ISSUE TITLE
SuperCDMS data tutorials

### ISSUE THREAD

**Issue by zonca** [pondd-project/pondd#5]
As discussed at our [last meeting](https://github.com/pondd-project/pondd-meetings/blob/main/meeting-notes/notes-20210824.md), it would be useful for me to start familiarize with the data looking at the SuperCDMS tutorials.

@pibion do you have pointers?

(no hurry, I am still wrapping up another project, but I'll recover later on)

**Comment by pibion** [comment]
@zonca yes, there are actually a couple tutorials for you to take an initial look at!  Is your GitLab username the same as on GitHub?

**Comment by zonca** [comment]
> @zonca yes, there are actually a couple tutorials for you to take an initial look at!  Is your GitLab username the same as on GitHub?

Yes

**Comment by zonca** [comment]
@pibion I see you gave me access to more repos on Gitlab, I see one named `tutorials`, is that the one?

**Comment by pibion** [comment]
@zonca that is the one!  We are also starting to have a tutorial in the RQAnalysis repo, but that one is still experimental.  We'll move it over to the `tutorials` once it's finalized.

**Comment by zonca** [comment]
@pibion I opened an issue in that repository related to installing the `cdms` package,
is there another preferred way to get support? Even if it is slack I can join slack.

**Comment by pibion** [comment]
@zonca on XSEDE you need to open a terminal and type `install_cdms_kernels`.  When you open the tutorial notebook, we recommend using the highest-number released for the kernel.

Sorry this took so long for me to post!  The things we need to make sure you have access to are the CDMS confluence page (if you can access https://confluence.slac.stanford.edu/display/CDMS/Accessing+XSEDE then you're good) and the gitlab repos.

If you're willing to try slack then it would be great to have you on our project channel.

**Comment by zonca** [comment]
@pibion yes, please invite me to that channel.

**Comment by zonca** [comment]
it seems I had an account `zonca` on the SLAC confluence, but password is not accepted and there is no "Password reset" option.

**Comment by zonca** [comment]
* Went through the Introduction tutorial, lots of terminology and processes I don't understand but the software works fine, the API of the software itself seems very complicated to use.
* all other tutorials require `uproot`, the fact this is not in the CDMS kernels is strange, do I need to install it myself? which other tutorial would be useful for me?

**Comment by zonca** [comment]
I think it would be useful to read a few papers that explain data processing for CDMS or similar experiments, would you have pointers?

**Comment by pibion** [comment]
There aren't any great papers that I know of (I should probably write one).

If you make an Open Science Framework account I can add you to a project
where we have a number of talks that present the basics.  It's a little
scattered but may be useful.

Once you have access to confluence I can point you to some additional talks
that are more in depth.

**Comment by zonca** [comment]
Yes I have a OSF account: https://osf.io/wexk3/

**Comment by zonca** [comment]
@pibion I found on OSF the video about salting with GAN, do you also have recordings for the cuts and the chi-squared talks?

My access to Confluence has been restored.

**Comment by pibion** [comment]
@zonca we do not, but I'll ask my student if he'd be interested in making these recordings!

**Comment by zonca** [comment]
@pibion please reopen of recordings are made available.
