### ISSUE TITLE
ytHub DID Finder

### ISSUE THREAD

**Issue by BenGalewsky** [pondd-project/pondd#9]
_As an astrophysicist I want to find yt datasets so I can analyze simulations _

# Assumptions
1. Will look for data from [ytHub](https://girder.hub.yt/#collections)
2. Will run as a service in ServiceX in the DIDFinder pattern 
 a. Listen for requests on RabbitMQ queue
 b. PUT each resulting file into the ServiceX transform via REST callback to the ServiceX app
3. Each result is a URI that can be opened by yt transformer
4. This will be quite similar to the [CERN OpenData DID Finder](https://github.com/ssl-hep/ServiceX_DID_Finder_CERNOpenData)

Notes:
```
curl -X GET --header 'Accept: application/json' 'https://girder.hub.yt/api/v1/item?text=snapshot_010&limit=50&sort=lowerName&sortdir=1' | jq
```

DID here is snapshot_010 Using example output it gives:
```json
  {
    "_id": "60cb7e1f68085e0001d2c6d6",
    "_modelType": "item",
    "_textScore": 6.666666666666666,
    "baseParentId": "5771413d95fe2100016477f3",
    "baseParentType": "collection",
    "created": "2021-06-17T16:53:51.587000+00:00",
    "creatorId": "56fab4e966a401000110bd00",
    "description": "",
    "folderId": "5e178e0868085e00016c2f73",
    "license": "",
    "meta": {
      "code": "Gadget",
      "description": "Cosmology output",
      "filename": "snapshot_010",
      "frontend": "sph",
      "load_kwargs": {},
      "load_name": "snapshot_010",
      "type": "dataset"
    },
    "name": "snapshot_010.tar.gz",
    "size": 102161346,
    "updated": "2021-06-17T18:38:04.802000+00:00"
  }
```

you can use that to download data immediately once you know the _id via

```shell
curl -X GET --header 'Accept: application/x-tar' 'https://girder.hub.yt/api/v1/item/60cb7e1f68085e0001d2c6d6/download?contentDisposition=attachment'
```

# Acceptance Criteria

**Comment by Michael-D-Johnson** [comment]
Initial version here: https://github.com/pondd-project/ServiceX_DID_Finder_Girder. Can iterate as we get feedback from yt users.
